name: Build

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Build Project with Production Config
        run: |
          npm run build
        env:
          CI: true

      - name: Push assets
        run: |
          shopify theme push \
            --json \
            --theme ${{ secrets.MAIN_THEME_ID }} \
            --store ${{ secrets.STORE_URL }} \
            --password ${{ secrets.API_ACCESS_TOKEN }} \
            --allow-live

